---
apiVersion: v1
kind: Service
metadata:
  name: hue-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: hue-exporter
  ports:
  - protocol: TCP
    port: 9366
    targetPort: metrics
