---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: loki-stack
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 2.4.1
  values:

    loki:
      persistence:
        enabled: true
        size: 2Gi
        storageClassName: microk8s-hostpath

    fluent-bit:
      enabled: true
      
    promtail:
      enabled: false
      
    grafana:
      enabled: true
      persistence:
        enabled: true
        size: 1Gi
        storageClassName: microk8s-hostpath
      image:
        tag: 7.0.3
      sidecar:
        dashboards:
          enabled: true
        datasources:
          enabled: false
      plugins:
        - flant-statusmap-panel
        - grafana-piechart-panel
      grafana.ini:
        server:
          domain: hal.rask.dk
          root_url: "https://hal.rask.dk/grafana"
          serve_from_sub_path: true

    prometheus:
      enabled: true

      alertmanager:
        persistentVolume:
          enabled: false
        service:
          loadBalancerIP: 192.168.0.14
          type: LoadBalancer

      server:
        extraFlags:
          - web.enable-lifecycle
          - storage.tsdb.wal-compression
        retention: "90d"
        persistentVolume:
          enabled: true
          size: 5Gi
          storageClassName: microk8s-hostpath
        service:
          loadBalancerIP: 192.168.0.13
          type: LoadBalancer
      extraScrapeConfigs: |
        - job_name: hue-exporter
          metrics_path: /metrics
          scrape_interval: 1m
          scrape_timeout: 30s
          static_configs:
            - targets:
              - hue-exporter.monitoring.svc:9366
        - job_name: pihole-exporter
          metrics_path: /metrics
          scrape_interval: 1m
          scrape_timeout: 30s
          static_configs:
            - targets:
              - pihole-exporter.monitoring.svc:9617
        - job_name: 'prometheus-blackbox-exporter'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets:
              - https://adfs.dfds.com/adfs/ls/IdpInitiatedSignOn.aspx
              - https://adfs.dfds.com/FederationMetadata/2007-06/FederationMetadata.xml
              - https://port.dfds.com/
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: prometheus-blackbox-exporter:9115
