---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: pihole-exporter
  ports:
  - protocol: TCP
    port: 9617
    targetPort: metrics
