---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foobar
  labels:
    app: foobar-nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: foobar-nginx
  template:
    metadata:
      labels:
        app: foobar-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.5
        ports:
        - name: web
          containerPort: 80