---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
  namespace: dvr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: dvr
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
      - name: bazarr-config-vol
        persistentVolumeClaim:
          claimName: bazarr-config-claim
      - name: dvr-tv-25g-vol
        persistentVolumeClaim:
          claimName: dvr-tv-25g-claim
      containers:
      - name: bazarr
        image: linuxserver/bazarr:latest
        ports:
        - name: web
          containerPort: 6767
        volumeMounts:
        - name: bazarr-config-vol
          mountPath: /config
        - name: dvr-tv-25g-vol
          mountPath: /tv
        env:
        - name: TZ
          value: Europe/Copenhagen

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: dvr
spec:
  type: ClusterIP
  selector:
    app: bazarr
  ports:
  - name: web
    protocol: TCP
    port: 6767
    targetPort: web
