---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvr-downloads-claim
  namespace: dvr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvr-tv-25g-claim
  namespace: dvr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
