---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: heimdall
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
