# https://github.com/causefx/Organizr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organizr-config-claim
  namespace: portal
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizr
  namespace: portal
  labels:
    app: organizr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizr
  template:
    metadata:
      labels:
        app: organizr
    spec:
      volumes:
      - name: organizr-config-volume
        persistentVolumeClaim:
          claimName: organizr-config-claim
      containers:
      - name: organizr
        image: organizrtools/organizr-v2:latest
        volumeMounts:
        - name: organizr-config-volume
          mountPath: /config
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: organizr
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: organizr
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
