---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-etc-claim
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-dnsmasq-claim
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      volumes:
      - name: pihole-local-etc-volume
        persistentVolumeClaim:
          claimName: pihole-local-etc-claim
      - name: pihole-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-local-dnsmasq-claim
      - name: dnsmasq-custom-hosts-volume
        configMap:
          name: dnsmasq-hosts
          items:
          - key: 10-custom-hosts.conf
            path: 10-custom-hosts.conf
          - key: custom.list
            path: custom.list
      initContainers:
      # Clearing the password in config, causes Pi-Hole to reset password from Env at start
      - name: clear-password
        image: busybox:1.28
        command:
        - sh
        - "-c"
        - if [ -e /etc/pihole/setupVars.conf ]; then sed -i "/WEBPASSWORD/d" "/etc/pihole/setupVars.conf" && echo Pihole password cleared from /etc/pihole/setupVars.conf; fi
        volumeMounts:
        - name: pihole-local-etc-volume
          mountPath: /etc/pihole
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - name: web
          containerPort: 80
        - name: dns-udp
          protocol: UDP
          containerPort: 53
        - name: dns-tcp
          protocol: TCP
          containerPort: 53
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-local-etc-volume
        - mountPath: /etc/dnsmasq.d
          name: pihole-local-dnsmasq-volume
        - mountPath: /etc/dnsmasq.d/10-custom-hosts.conf
          name: dnsmasq-custom-hosts-volume
          subPath: 10-custom-hosts.conf
        - mountPath: /etc/pihole/custom.list
          name: dnsmasq-custom-hosts-volume
          subPath: custom.list
        env:
        # Kubernetes accepts env variables only as strings - https://github.com/kubernetes/dashboard/issues/1603#issuecomment-311306926
        - name: ServerIP
          value: 192.168.0.10
        - name: VIRTUAL_HOST
          value: 192.168.0.10
        - name: DNS1
          value: 1.1.1.1
        - name: DNS2
          value: 1.0.0.1
        - name: TZ
          value: "Europe/Copenhagen"
        - name: DNS_FQDN_REQUIRED
          value: "false"
          # conditionally forward local queries to DHCP server - breaks DNS lookup, by appending local domain name to all queries?
        # - name: CONDITIONAL_FORWARDING
        #   value: "true"
        # - name: CONDITIONAL_FORWARDING_IP
        #   value: 192.168.0.2
        # - name: CONDITIONAL_FORWARDING_DOMAIN
        #   value: rask.local
        # - name: CONDITIONAL_FORWARDING_REVERSE
        #   value: 0.168.192.in-addr.arpa
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole
              key: WEBPASSWORD
