---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: portal
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: heimdall
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: heimdall
  namespace: portal
  annotations:
    # traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /heimdall
        backend:
          serviceName: heimdall
          servicePort: web


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: portal
spec:
  stripPrefix:
    prefixes:
    - /heimdall

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: replacepath
  namespace: portal
spec:
  replacePathRegex:
    regex: ^/heimdall/(.*)
    replacement: /$1

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall
  namespace: portal
spec:
  entrypoints:
  - http
  routes:
  - match: PathPrefix(`/heimdall`)
    kind: Rule
    services:
    - name: heimdall
      port: 80
    middlewares:
    - name: replacepath