# https://github.com/causefx/Organizr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizr
  namespace: portal
  labels:
    app: organizr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizr
  template:
    metadata:
      labels:
        app: organizr
    spec:
      containers:
      - name: organizr
        image: organizrtools/organizr-v2:latest
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: organizr
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: organizr
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: organizr
  namespace: portal
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /organizr
        backend:
          serviceName: organizr
          servicePort: web
