---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-v2_1-ext-crb

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-v2_1-cr
subjects:
  - kind: ServiceAccount
    name: traefik-ext-sa
    namespace: traefik
