---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-etc-claim
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-local-dnsmasq-claim
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      # Clearing the password in config, causes Pi-Hole to reset password from Env at start
      initContainers:
      - name: clear-password
        image: busybox:1.28
        command:
        - sh
        - "-c"
        - if [ -e /etc/pihole/setupVars.conf ]; then sed -i "/WEBPASSWORD/d" "/etc/pihole/setupVars.conf" && echo Pihole password cleared from /etc/pihole/setupVars.conf; fi
        volumeMounts:
        - name: pihole-local-etc-volume
          mountPath: "/etc/pihole"
      containers:
      - name: pihole
        image: pihole/pihole:latest
        # imagePullPolicy: Always
        env:
        # - name: ServerIP
          # value: 192.168.0.4
        - name: VIRTUAL_HOST
          value: 192.168.0.4:8000
          # value: 192.168.0.4:30000/pihole
        - name: DNS1
          value: 91.239.100.100
        - name: DNS2
          value: 89.233.43.71
        - name: TZ
          value: "Europe/Copenhagen"
        - name: DNS_FQDN_REQUIRED
          value: false
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole
              key: WEBPASSWORD
        volumeMounts:
        - name: pihole-local-etc-volume
          mountPath: "/etc/pihole"
        - name: pihole-local-dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: pihole-local-etc-volume
        persistentVolumeClaim:
          claimName: pihole-local-etc-claim
      - name: pihole-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-local-dnsmasq-claim

---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - port: 8000
    # nodePort: 8000
    targetPort: 80
    name: web
  - port: 53
    # nodePort: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    # nodePort: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  # Attempt to preserve source IP - https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  # Does not seem to work, possibly because accessing via service port, not nodeport
  externalTrafficPolicy: Local
  externalIPs:
  - 192.168.0.4
  
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pihole
  namespace: pihole
  # annotations:
    # traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /pihole
        backend:
          serviceName: pihole
          servicePort: web