---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ext-sa
  namespace: traefik

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-ext-claim
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ext
  namespace: traefik
  labels:
    k8s-app: traefik-ext
spec:
  selector:
    matchLabels:
      name: traefik-ext
  template:
    metadata:
      labels:
        name: traefik-ext
        app: traefik-ext
        k8s-app: traefik-ext
    spec:
      volumes:
        - name: traefik-ext-volume
          persistentVolumeClaim:
            claimName: traefik-ext-claim
      serviceAccountName: traefik-ext-sa
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v2.4
          # imagePullPolicy: Always
          name: traefik
          volumeMounts:
            - mountPath: /etc/traefik
              name: traefik-ext-volume
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: traefik
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --global.sendAnonymousUsage=true
            - --log=true
            - --log.level=INFO
            - --accesslog=true
            - --api=true
            - --api.dashboard=true
            - --api.insecure=true
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --ping=true
            - --providers.kubernetesCRD
            - --certificatesresolvers.default.acme.email=hostmaster@rask.dk
            - --certificatesresolvers.default.acme.storage=/etc/traefik/acme.json
            - --certificatesresolvers.default.acme.tlschallenge=true
          # - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory # Debugging only
          # - --serverstransport.insecureskipverify

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ext
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ext
  loadBalancerIP: 192.168.0.10
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: traefik
      protocol: TCP
      port: 8080
