# https://docs.linuxserver.io/images/docker-heimdall

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config-claim
  namespace: portal
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: portal
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
      - name: heimdall-config-volume
        persistentVolumeClaim:
          claimName: heimdall-config-claim
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        volumeMounts:
        - name: heimdall-config-volume
          mountPath: /config
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: portal
spec:
  type: ClusterIP
  selector:
    app: heimdall
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall
  namespace: portal
spec:
  entrypoints:
  - https
  routes:
  - match: Host(`heimdall.rask.dk`)
    kind: Rule
    services:
    - name: heimdall
      port: 80
    middlewares:
    - name: traefik-auth
      namespace: traefik
  tls:
    certResolver: default
