# https://docs.linuxserver.io/images/docker-heimdall

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config-claim
  namespace: portal
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: portal
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
      - name: heimdall-config-volume
        persistentVolumeClaim:
          claimName: heimdall-config-claim
      containers:
      - name: heimdall
        image: linuxserver/heimdall:latest
        volumeMounts:
        - name: heimdall-config-volume
          mountPath: /config
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
