# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: pihole
#   namespace: pihole
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/rule-type: PathPrefix
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /pihole
#         backend:
#           serviceName: pihole
#           servicePort: web

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entrypoints:
    - http
  routes:
  - match: PathPrefix(`/pihole`)
    kind: Rule
    services:
    - name: pihole
      port: web
